In [6]:
# ============================================
# 1. Import Required Libraries
# ============================================

import pandas as pd
import numpy as np


# ============================================
# 2. Load the Original Dataset
# ============================================

df = pd.read_csv("Telco-Customer-Churn.csv")


# ============================================
# 3. Display Dataset Shape
# ============================================

print("Shape of the Dataset:")
print(df.shape)


# ============================================
# 4. Display First 5 Rows
# ============================================

print("\nFirst 5 Rows:")
display(df.head())


# ============================================
# 5. Display All Column Names
# ============================================

print("\nColumn Names:")
print(df.columns.tolist())


# ============================================
# 6. Display Data Types
# ============================================

print("\nData Types:")
display(df.dtypes)


# ============================================
# 7. Display Missing Values
# ============================================

print("\nMissing Values:")
display(df.isnull().sum())


# ============================================
# 8. Display Duplicate Rows
# ============================================

print("\nNumber of Duplicate Rows:")
print(df.duplicated().sum())

Shape of the Dataset:
(7043, 21)

First 5 Rows:

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

Column Names:
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

Data Types:

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

Missing Values:

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Number of Duplicate Rows:
0

In [7]:
# ============================================
# 1. Remove CustomerID Column
# ============================================

df = df.drop(columns=["customerID"])


# ============================================
# 2. Convert TotalCharges to Numeric
# ============================================

df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)


# ============================================
# 3. Convert Churn from Yes/No to 1/0
# ============================================

df["Churn"] = df["Churn"].map({
    "No": 0,
    "Yes": 1
})


# ============================================
# 4. Handle Missing Values in TotalCharges
# ============================================

print("Missing values in TotalCharges before handling:")
print(df["TotalCharges"].isnull().sum())

# Fill missing TotalCharges values with 0
df["TotalCharges"] = df["TotalCharges"].fillna(0)


# ============================================
# 5. Check for Duplicate Rows
# ============================================

duplicate_count = df.duplicated().sum()

print("\nNumber of Duplicate Rows:")
print(duplicate_count)


# ============================================
# 6. Remove Duplicate Rows if Any Exist
# ============================================

if duplicate_count > 0:
    df = df.drop_duplicates()
    print("Duplicate rows removed.")
else:
    print("No duplicate rows found.")


# ============================================
# 7. Display Final Shape
# ============================================

print("\nFinal Shape After Cleaning:")
print(df.shape)


# ============================================
# 8. Display Missing Values After Cleaning
# ============================================

print("\nMissing Values After Cleaning:")
display(df.isnull().sum())


# ============================================
# 9. Display Target Distribution
# ============================================

print("\nTarget Distribution:")
display(df["Churn"].value_counts())

print("\nTarget Distribution in Percentage:")
display(
    df["Churn"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Missing values in TotalCharges before handling:
11

Number of Duplicate Rows:
22
Duplicate rows removed.

Final Shape After Cleaning:
(7021, 20)

Missing Values After Cleaning:

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

Target Distribution:

Churn
0    5164
1    1857
Name: count, dtype: int64

Target Distribution in Percentage:

Churn
0    73.55
1    26.45
Name: proportion, dtype: float64

In [8]:
# ============================================
# 1. Separate Features and Target
# ============================================

# X contains all predictor features
X = df.drop(columns=["Churn"])

# y contains the target variable
y = df["Churn"]


# ============================================
# 2. Display Shape of X and y
# ============================================

print("Shape of X (Features):")
print(X.shape)

print("\nShape of y (Target):")
print(y.shape)


# ============================================
# 3. Display First 5 Rows of X
# ============================================

print("\nFirst 5 Rows of X:")
display(X.head())


# ============================================
# 4. Display First 5 Values of y
# ============================================

print("\nFirst 5 Values of y:")
display(y.head())


# ============================================
# 5. Display Class Distribution of y
# ============================================

print("\nClass Distribution of y:")
display(y.value_counts().sort_index())


# ============================================
# 6. Display Percentage Distribution of y
# ============================================

print("\nPercentage Distribution of y:")

y_percentage = (
    y.value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

display(y_percentage)

Shape of X (Features):
(7021, 19)

Shape of y (Target):
(7021,)

First 5 Rows of X:

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65

First 5 Values of y:

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

Class Distribution of y:

Churn
0    5164
1    1857
Name: count, dtype: int64

Percentage Distribution of y:

Churn
0    73.55
1    26.45
Name: proportion, dtype: float64

In [9]:
# ============================================
# 1. Import train_test_split
# ============================================

from sklearn.model_selection import train_test_split


# ============================================
# 2. Split Dataset into Training and Testing
# ============================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


# ============================================
# 3. Display Shapes of All Datasets
# ============================================

print("Shape of X_train:")
print(X_train.shape)

print("\nShape of X_test:")
print(X_test.shape)

print("\nShape of y_train:")
print(y_train.shape)

print("\nShape of y_test:")
print(y_test.shape)


# ============================================
# 4. Display Target Distribution in y_train
# ============================================

print("\nTarget Distribution in y_train:")
display(y_train.value_counts().sort_index())


# ============================================
# 5. Display Target Distribution in y_test
# ============================================

print("\nTarget Distribution in y_test:")
display(y_test.value_counts().sort_index())


# ============================================
# 6. Display Target Percentage Distribution
#    in Training and Testing Sets
# ============================================

print("\nTarget Percentage Distribution in y_train:")
display(
    y_train.value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

print("\nTarget Percentage Distribution in y_test:")
display(
    y_test.value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

Shape of X_train:
(5616, 19)

Shape of X_test:
(1405, 19)

Shape of y_train:
(5616,)

Shape of y_test:
(1405,)

Target Distribution in y_train:

Churn
0    4131
1    1485
Name: count, dtype: int64

Target Distribution in y_test:

Churn
0    1033
1     372
Name: count, dtype: int64

Target Percentage Distribution in y_train:

Churn
0    73.56
1    26.44
Name: proportion, dtype: float64

Target Percentage Distribution in y_test:

Churn
0    73.52
1    26.48
Name: proportion, dtype: float64

In [10]:
# ============================================
# 1. Identify Numerical Features
# ============================================

numerical_features = X_train.select_dtypes(
    include=np.number
).columns.tolist()


# ============================================
# 2. Identify Categorical Features
# ============================================

categorical_features = X_train.select_dtypes(
    exclude=np.number
).columns.tolist()


# ============================================
# 3. Print Numerical Features
# ============================================

print("Numerical Features:")
print(numerical_features)

print("\nNumber of Numerical Features:")
print(len(numerical_features))


# ============================================
# 4. Print Categorical Features
# ============================================

print("\nCategorical Features:")
print(categorical_features)

print("\nNumber of Categorical Features:")
print(len(categorical_features))


# ============================================
# 5. Verify All Features Belong to One Group
# ============================================

all_identified_features = (
    numerical_features + categorical_features
)

all_features_identified = (
    set(X_train.columns) == set(all_identified_features)
)

print("\nFeature Group Verification:")

if all_features_identified:
    print("All features in X_train belong to either numerical_features or categorical_features.")
else:
    print("Warning: Some features in X_train are not included in either group.")


# ============================================
# 6. Verify No Feature Appears in Both Groups
# ============================================

overlapping_features = set(numerical_features).intersection(
    set(categorical_features)
)

print("\nOverlapping Features:")

if len(overlapping_features) == 0:
    print("No feature appears in both groups.")
else:
    print("Features appearing in both groups:")
    print(overlapping_features)

Numerical Features:
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

Number of Numerical Features:
4

Categorical Features:
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

Number of Categorical Features:
15

Feature Group Verification:
All features in X_train belong to either numerical_features or categorical_features.

Overlapping Features:
No feature appears in both groups.

In [11]:
# ============================================
# Numerical Preprocessing Pipeline
# ============================================

# Import required preprocessing tools
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline


# ============================================
# Create Numerical Preprocessing Pipeline
# ============================================

numerical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)


# ============================================
# Display Pipeline Structure
# ============================================

print("Numerical Preprocessing Pipeline:")
print(numerical_transformer)

Numerical Preprocessing Pipeline:
Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [12]:
# ============================================
# Categorical Preprocessing Pipeline
# ============================================

# Import required preprocessing tools
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline


# ============================================
# Create Categorical Preprocessing Pipeline
# ============================================

categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        (
            "encoder",
            OneHotEncoder(handle_unknown="ignore")
        )
    ]
)


# ============================================
# Display Pipeline Structure
# ============================================

print("Categorical Preprocessing Pipeline:")
print(categorical_transformer)

Categorical Preprocessing Pipeline:
Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore'))])

In [13]:
# ============================================
# Create Combined Preprocessing Pipeline
# ============================================

from sklearn.compose import ColumnTransformer


# ============================================
# Create ColumnTransformer
# ============================================

preprocessor = ColumnTransformer(
    transformers=[
        ("numerical", numerical_transformer, numerical_features),
        ("categorical", categorical_transformer, categorical_features)
    ],
    remainder="drop"
)


# ============================================
# Display Preprocessor Structure
# ============================================

print("Combined Preprocessing Pipeline:")
print(preprocessor)

Combined Preprocessing Pipeline:
ColumnTransformer(transformers=[('numerical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['SeniorCitizen', 'tenure', 'MonthlyCharges',
                                  'TotalCharges']),
                                ('categorical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'Partner', 'Dependents',
                                  'PhoneService', 'MultipleLines',
                                  'InternetService', 'OnlineSecurity',
                                  'OnlineBackup', 'DeviceProtection',
                                  'TechSupport', 'StreamingTV',
                                  'StreamingMovies', 'Contract',
                                  'PaperlessBilling', 'PaymentMethod'])])

In [14]:
# ============================================
# Fit and Transform Preprocessing Pipeline
# ============================================

# Fit the preprocessor only on the training data
preprocessor.fit(X_train)


# ============================================
# Transform Training Data
# ============================================

X_train_processed = preprocessor.transform(X_train)


# ============================================
# Transform Testing Data
# ============================================

# Use the already-fitted preprocessor
# Do NOT fit the preprocessor again on X_test
X_test_processed = preprocessor.transform(X_test)


# ============================================
# Display Processed Data Shapes
# ============================================

print("Shape of X_train_processed:")
print(X_train_processed.shape)

print("\nShape of X_test_processed:")
print(X_test_processed.shape)


# ============================================
# Verify Number of Rows
# ============================================

print("\nRow Count Verification:")

print(
    f"X_train original rows: {X_train.shape[0]}"
)
print(
    f"X_train_processed rows: {X_train_processed.shape[0]}"
)

print(
    f"X_test original rows: {X_test.shape[0]}"
)
print(
    f"X_test_processed rows: {X_test_processed.shape[0]}"
)


# ============================================
# Verify Row Counts Match
# ============================================

train_rows_match = (
    X_train.shape[0] == X_train_processed.shape[0]
)

test_rows_match = (
    X_test.shape[0] == X_test_processed.shape[0]
)

print("\nRow Count Verification Results:")

print(
    f"Training rows match: {train_rows_match}"
)

print(
    f"Testing rows match: {test_rows_match}"
)

Shape of X_train_processed:
(5616, 45)

Shape of X_test_processed:
(1405, 45)

Row Count Verification:
X_train original rows: 5616
X_train_processed rows: 5616
X_test original rows: 1405
X_test_processed rows: 1405

Row Count Verification Results:
Training rows match: True
Testing rows match: True

In [15]:
# ============================================
# Retrieve Final Feature Names
# ============================================

# Extract feature names generated by the fitted preprocessor
feature_names = preprocessor.get_feature_names_out().tolist()


# ============================================
# Display Total Number of Final Features
# ============================================

print("Total Number of Final Features:")
print(len(feature_names))


# ============================================
# Display All Final Feature Names
# ============================================

print("\nFinal Feature Names:")

for i, feature in enumerate(feature_names, start=1):
    print(f"{i}. {feature}")


# ============================================
# Verify Feature Count
# ============================================

print("\nFeature Count Verification:")

print(
    f"Number of feature names: {len(feature_names)}"
)

print(
    f"Number of columns in X_train_processed: "
    f"{X_train_processed.shape[1]}"
)


# ============================================
# Check Whether Feature Counts Match
# ============================================

feature_count_matches = (
    len(feature_names) == X_train_processed.shape[1]
)

print(
    f"\nFeature count matches: {feature_count_matches}"
)

Total Number of Final Features:
45

Final Feature Names:
1. numerical__SeniorCitizen
2. numerical__tenure
3. numerical__MonthlyCharges
4. numerical__TotalCharges
5. categorical__gender_Female
6. categorical__gender_Male
7. categorical__Partner_No
8. categorical__Partner_Yes
9. categorical__Dependents_No
10. categorical__Dependents_Yes
11. categorical__PhoneService_No
12. categorical__PhoneService_Yes
13. categorical__MultipleLines_No
14. categorical__MultipleLines_No phone service
15. categorical__MultipleLines_Yes
16. categorical__InternetService_DSL
17. categorical__InternetService_Fiber optic
18. categorical__InternetService_No
19. categorical__OnlineSecurity_No
20. categorical__OnlineSecurity_No internet service
21. categorical__OnlineSecurity_Yes
22. categorical__OnlineBackup_No
23. categorical__OnlineBackup_No internet service
24. categorical__OnlineBackup_Yes
25. categorical__DeviceProtection_No
26. categorical__DeviceProtection_No internet service
27. categorical__DeviceProtection_Yes
28. categorical__TechSupport_No
29. categorical__TechSupport_No internet service
30. categorical__TechSupport_Yes
31. categorical__StreamingTV_No
32. categorical__StreamingTV_No internet service
33. categorical__StreamingTV_Yes
34. categorical__StreamingMovies_No
35. categorical__StreamingMovies_No internet service
36. categorical__StreamingMovies_Yes
37. categorical__Contract_Month-to-month
38. categorical__Contract_One year
39. categorical__Contract_Two year
40. categorical__PaperlessBilling_No
41. categorical__PaperlessBilling_Yes
42. categorical__PaymentMethod_Bank transfer (automatic)
43. categorical__PaymentMethod_Credit card (automatic)
44. categorical__PaymentMethod_Electronic check
45. categorical__PaymentMethod_Mailed check

Feature Count Verification:
Number of feature names: 45
Number of columns in X_train_processed: 45

Feature count matches: True

In [16]:
# ============================================
# Apply SMOTE to Training Data Only
# ============================================

from imblearn.over_sampling import SMOTE


# ============================================
# 1. Display Class Distribution Before SMOTE
# ============================================

print("Class Distribution Before SMOTE:")
display(y_train.value_counts().sort_index())


# ============================================
# 2. Display Shapes Before SMOTE
# ============================================

print("\nShapes Before SMOTE:")
print(f"X_train_processed: {X_train_processed.shape}")
print(f"y_train: {y_train.shape}")


# ============================================
# 3. Create SMOTE Object
# ============================================

smote = SMOTE(random_state=42)


# ============================================
# 4. Apply SMOTE Only to Training Data
# ============================================

# SMOTE is applied only to the training data because applying it
# to the test data would cause data leakage and make evaluation
# results unreliable. The test set must remain untouched and
# represent the original real-world class distribution.

X_train_resampled, y_train_resampled = smote.fit_resample(
    X_train_processed,
    y_train
)


# ============================================
# 5. Display Class Distribution After SMOTE
# ============================================

print("\nClass Distribution After SMOTE:")
display(y_train_resampled.value_counts().sort_index())


# ============================================
# 6. Display Shapes After SMOTE
# ============================================

print("\nShapes After SMOTE:")
print(f"X_train_resampled: {X_train_resampled.shape}")
print(f"y_train_resampled: {y_train_resampled.shape}")


# ============================================
# 7. Final SMOTE Verification
# ============================================

print("\nSMOTE Verification:")
print(
    f"Training samples before SMOTE: {X_train_processed.shape[0]}"
)
print(
    f"Training samples after SMOTE: {X_train_resampled.shape[0]}"
)

print(
    f"Test samples (unchanged): {X_test_processed.shape[0]}"
)

Class Distribution Before SMOTE:

Churn
0    4131
1    1485
Name: count, dtype: int64

Shapes Before SMOTE:
X_train_processed: (5616, 45)
y_train: (5616,)

Class Distribution After SMOTE:

Churn
0    4131
1    4131
Name: count, dtype: int64

Shapes After SMOTE:
X_train_resampled: (8262, 45)
y_train_resampled: (8262,)

SMOTE Verification:
Training samples before SMOTE: 5616
Training samples after SMOTE: 8262
Test samples (unchanged): 1405

In [17]:
print("X_train_resampled:", X_train_resampled.shape)
print("y_train_resampled:", y_train_resampled.shape)
print("X_test_processed:", X_test_processed.shape)
print("y_test:", y_test.shape)
print("feature_names:", len(feature_names))

X_train_resampled: (8262, 45)
y_train_resampled: (8262,)
X_test_processed: (1405, 45)
y_test: (1405,)
feature_names: 45

In [18]:
# ============================================
# Final Preprocessing Validation
# ============================================


# ============================================
# 1. Display Shapes of Training and Testing Data
# ============================================

print("=" * 60)
print("1. DATASET SHAPES")
print("=" * 60)

print(f"X_train_resampled: {X_train_resampled.shape}")
print(f"y_train_resampled: {y_train_resampled.shape}")
print(f"X_test_processed: {X_test_processed.shape}")
print(f"y_test: {y_test.shape}")


# ============================================
# 2. Target Class Distribution Before SMOTE
# ============================================

print("\n" + "=" * 60)
print("2. TARGET DISTRIBUTION BEFORE SMOTE")
print("=" * 60)

print("y_train:")
display(y_train.value_counts().sort_index())


# ============================================
# 3. Target Class Distribution After SMOTE
# ============================================

print("\n" + "=" * 60)
print("3. TARGET DISTRIBUTION AFTER SMOTE")
print("=" * 60)

print("y_train_resampled:")
display(y_train_resampled.value_counts().sort_index())


# ============================================
# 4. Check for NaN Values
# ============================================

print("\n" + "=" * 60)
print("4. NaN VALUE CHECK")
print("=" * 60)

# Check NaN values in processed training data
if hasattr(X_train_resampled, "toarray"):
    train_nan_count = np.isnan(X_train_resampled.toarray()).sum()
else:
    train_nan_count = np.isnan(X_train_resampled).sum()

# Check NaN values in processed testing data
if hasattr(X_test_processed, "toarray"):
    test_nan_count = np.isnan(X_test_processed.toarray()).sum()
else:
    test_nan_count = np.isnan(X_test_processed).sum()

print(f"NaN values in X_train_resampled: {train_nan_count}")
print(f"NaN values in X_test_processed: {test_nan_count}")


# ============================================
# 5. Check for Infinite Values
# ============================================

print("\n" + "=" * 60)
print("5. INFINITE VALUE CHECK")
print("=" * 60)

# Check infinite values in processed training data
if hasattr(X_train_resampled, "toarray"):
    train_inf_count = np.isinf(X_train_resampled.toarray()).sum()
else:
    train_inf_count = np.isinf(X_train_resampled).sum()

# Check infinite values in processed testing data
if hasattr(X_test_processed, "toarray"):
    test_inf_count = np.isinf(X_test_processed.toarray()).sum()
else:
    test_inf_count = np.isinf(X_test_processed).sum()

print(f"Infinite values in X_train_resampled: {train_inf_count}")
print(f"Infinite values in X_test_processed: {test_inf_count}")


# ============================================
# 6. Verify Feature Count Matches feature_names
# ============================================

print("\n" + "=" * 60)
print("6. FEATURE COUNT VERIFICATION")
print("=" * 60)

train_feature_count = X_train_resampled.shape[1]
test_feature_count = X_test_processed.shape[1]
feature_names_count = len(feature_names)

print(f"Number of feature names: {feature_names_count}")
print(f"Training feature columns: {train_feature_count}")
print(f"Testing feature columns: {test_feature_count}")

train_features_match = (
    train_feature_count == feature_names_count
)

test_features_match = (
    test_feature_count == feature_names_count
)

print(f"\nTraining features match feature_names: {train_features_match}")
print(f"Testing features match feature_names: {test_features_match}")


# ============================================
# 7. Final Preprocessing Validation
# ============================================

print("\n" + "=" * 60)
print("7. FINAL PREPROCESSING SUMMARY")
print("=" * 60)

preprocessing_complete = (
    train_nan_count == 0
    and test_nan_count == 0
    and train_inf_count == 0
    and test_inf_count == 0
    and train_features_match
    and test_features_match
)

if preprocessing_complete:
    print("Preprocessing validation completed successfully.")
    print("✓ Training and testing data have the expected shapes.")
    print("✓ SMOTE was applied to the training data.")
    print("✓ No NaN values found in processed data.")
    print("✓ No infinite values found in processed data.")
    print("✓ Feature counts match feature_names.")
    print("\nData preprocessing is complete and ready for model training.")
else:
    print("Warning: Preprocessing validation found one or more issues.")
    print("Please review the validation results above before model training.")

============================================================
1. DATASET SHAPES
============================================================
X_train_resampled: (8262, 45)
y_train_resampled: (8262,)
X_test_processed: (1405, 45)
y_test: (1405,)

============================================================
2. TARGET DISTRIBUTION BEFORE SMOTE
============================================================
y_train:

Churn
0    4131
1    1485
Name: count, dtype: int64

============================================================
3. TARGET DISTRIBUTION AFTER SMOTE
============================================================
y_train_resampled:

Churn
0    4131
1    4131
Name: count, dtype: int64

============================================================
4. NaN VALUE CHECK
============================================================
NaN values in X_train_resampled: 0
NaN values in X_test_processed: 0

============================================================
5. INFINITE VALUE CHECK
============================================================
Infinite values in X_train_resampled: 0
Infinite values in X_test_processed: 0

============================================================
6. FEATURE COUNT VERIFICATION
============================================================
Number of feature names: 45
Training feature columns: 45
Testing feature columns: 45

Training features match feature_names: True
Testing features match feature_names: True

============================================================
7. FINAL PREPROCESSING SUMMARY
============================================================
Preprocessing validation completed successfully.
✓ Training and testing data have the expected shapes.
✓ SMOTE was applied to the training data.
✓ No NaN values found in processed data.
✓ No infinite values found in processed data.
✓ Feature counts match feature_names.

Data preprocessing is complete and ready for model training.

In [19]:
import joblib



# Save original test data
joblib.dump(
    X_test,
    "X_test.pkl"
)

# Save processed test data
joblib.dump(
    X_test_processed,
    "X_test_processed.pkl"
)

# Save test labels
joblib.dump(
    y_test,
    "y_test.pkl"
)

# Save feature names
joblib.dump(
    feature_names,
    "feature_names.pkl"
)

print("All preprocessing artifacts saved successfully!")
print("X_test shape:", X_test.shape)
print("X_test_processed shape:", X_test_processed.shape)
print("y_test shape:", y_test.shape)
print("MonthlyCharges available:", "MonthlyCharges" in X_test.columns)

All preprocessing artifacts saved successfully!
X_test shape: (1405, 19)
X_test_processed shape: (1405, 45)
y_test shape: (1405,)
MonthlyCharges available: True